[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.proto]
command = "clang-format"
options = [ "-i" ]
includes = [ "*.proto" ]

[formatter.sql]
command = "sql-formatter-writer"
includes = [ "*.sql" ]
