schema = 3

[mod]
  [mod."github.com/golang/glog"]
    version = "v1.0.0"
    hash = "sha256-bglITqRgzi52zc6FoYYnfCvrjFWV4RVOacPCnbEBom4="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.11.3"
    hash = "sha256-jnuNObVfKtdS/YZWNG17aRtKskG3gieSHGOBgyOcTmg="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220826154423-83b083e8dc8b"
    hash = "sha256-50A1EeE7HxKbnLBy1vdxtrbH+7d6/mnZA0cOwHJr5XA="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220829200755-d48e67d00261"
    hash = "sha256-59QemXKVd6kAYAL5fWHfJJHKc1Hi+uzZlzumigha9jE="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20220829175752-36a9c930ecbf"
    hash = "sha256-Vm1kzaSMQBbG9XAs8rr8jM5kl635o6d/BH0+5lKPZzs="
  [mod."google.golang.org/grpc"]
    version = "v1.49.0"
    hash = "sha256-x4+/XjxI2HY8fZYMiEV7Kv+2SrnlmaTJX3tBl+dPUoI="
  [mod."google.golang.org/grpc/cmd/protoc-gen-go-grpc"]
    version = "v1.2.0"
    hash = "sha256-TmqEJBuLUom7FgJkCwF5pyebbKpzzZ51AxhKm2o3TuA="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
