[cron]
log_index = 900

[lognames]
e0f263745e4e3ab07ab5275b00b44f594e0b6d2bd35892a8ebd10a7f86322eb7 = "trustix-demo"

[attrs]
nixos-unstable = [
  "nixos.iso_minimal.x86_64-linux"
]

[channels.hydra.nixos-unstable]
base_url = "https://hydra.nixos.org"
jobset = "trunk-combined"
project = "nixos"
interval = 3600
