log_poll_interval = 900

[lognames]
e0f263745e4e3ab07ab5275b00b44f594e0b6d2bd35892a8ebd10a7f86322eb7 = "trustix-demo"

[attrs]
nixos-unstable = [
  "nixos.iso_minimal.x86_64-linux"
]

# Note that this is the correct schema but as this file is used for the development config the hydra import is commented out.
# [channels.hydra.nixos-unstable]
# base_url = "https://hydra.nixos.org"
# jobset = "trunk-combined"
# project = "nixos"
# interval = 3600
