schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v1.2.0"
    hash = "sha256-yxBUbKQ3v4Na9IHDf4PLePrILAX4kmk2Zc+kqWazlIY="
  [mod."github.com/ClickHouse/clickhouse-go"]
    version = "v1.5.4"
    hash = "sha256-De5oreE/B/y5fjlFzxDafjr7wGjnAPPooqOFTGtuSoA="
  [mod."github.com/adrg/xdg"]
    version = "v0.4.0"
    hash = "sha256-zGjkdUQmrVqD6rMO9oDY+TeJCpuqnHyvkPCaXDlac/U="
  [mod."github.com/antlr/antlr4/runtime/Go/antlr"]
    version = "v0.0.0-20220626175859-9abda183db8e"
    hash = "sha256-QZn1eltqxkZYvf7g/GQv6HftH+OuKJTVjIjyyHZw9jI="
  [mod."github.com/bakins/logrus-middleware"]
    version = "v0.0.0-20180426214643-ce4c6f8deb07"
    hash = "sha256-8BaMIVqeDOfbM+PN6IyHHsu3pOUO/hqrGT/+HaECZjo="
  [mod."github.com/bufbuild/connect-go"]
    version = "v0.5.0"
    hash = "sha256-ZqhGTTClckSAqvzNwy/lrQ/MGr6DZghOzSnoKDOuJw8="
  [mod."github.com/buger/jsonparser"]
    version = "v1.1.1"
    hash = "sha256-T6dXT6Vzpm8gvQYi+c2LZkV+8ZOp0ZXBX7+e1mlliZE="
  [mod."github.com/bytecodealliance/wasmtime-go"]
    version = "v0.39.0"
    hash = "sha256-RtWZpY0vulO5VcQDlsXvCsKFdA18+l0erExbWf3Y+9A="
  [mod."github.com/cloudflare/golz4"]
    version = "v0.0.0-20150217214814-ef862a3cdc58"
    hash = "sha256-we6f7JwDfq9PQ+w9ey8yBwELnBhtmzht0yAApcblcTI="
  [mod."github.com/coreos/go-systemd"]
    version = "v0.0.0-20191104093116-d3cd4ed1dbcf"
    hash = "sha256-HEnyJ9uxZdlZb2lG8YwxYuuYTCW8PpxUhADqEwNlN5U="
  [mod."github.com/cznic/mathutil"]
    version = "v0.0.0-20181122101859-297441e03548"
    hash = "sha256-PdMEn2mI6RASqkG7G8wsvjpRsEoHpSWWXG/iwC8KeaM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/denisenkom/go-mssqldb"]
    version = "v0.12.2"
    hash = "sha256-Z2tewWs/676gd8FDTos6/fPH/5XLNQ+UmZ+N5Kw30gI="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.6.0"
    hash = "sha256-mMIiUN5XUXxYOpdlMQMFzYB4AX2xrpGgkkEBL0jLKrg="
  [mod."github.com/golang-sql/civil"]
    version = "v0.0.0-20220223132316-b832511892a9"
    hash = "sha256-IEz9BkkHyFfs9R4aMxH/c/tD510qSyFEaKrpO4arWpQ="
  [mod."github.com/golang-sql/sqlexp"]
    version = "v0.1.0"
    hash = "sha256-FhKWdt7vwzTbIsx2u+AzrKO1VFxTw/lbgD9/V5G76jw="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/hashicorp/go-uuid"]
    version = "v1.0.3"
    hash = "sha256-8893qBbaug2yhxElowSrl3PrfhYlQ7cZ71QBgZWqpHE="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.4"
    hash = "sha256-1skUMZX+iIf66J1TBVYGWO1OWwQcaoXut3mne331q+k="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.1"
    hash = "sha256-ZTP9pLgwAAvHYK5A4PqwWCHGt00x5zMSOpCPoomQ3Sg="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.1.1"
    hash = "sha256-Ru6KSK9N08IxuwinJA1c+1zA04rTY8kcHBcKThMqZkE="
  [mod."github.com/kyleconroy/sqlc"]
    version = "v1.15.0"
    hash = "sha256-MzeNP+G9g507G9s0wTZfQLVHGYKilMoBXClANEP+oH0="
  [mod."github.com/lib/pq"]
    version = "v1.10.6"
    hash = "sha256-8EhFwY/9YH5L/fd6l2beOnC3VvpegRAmCCsnDVJBqBM="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.15"
    hash = "sha256-fSrs2sdBKFTAiffBHNnAkN8kDTqiXgm4HNqzJAOF1RM="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.0"
    hash = "sha256-oEo/BoMqSLdwSjrhHTiFjl5Om4MVLNQXDJINk6Z110Y="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/multiformats/go-multihash"]
    version = "v0.2.1"
    hash = "sha256-RWyw05s4Wnz44J2YzPkJAK/A4l5V4ZGk/c2I4lW18wc="
  [mod."github.com/multiformats/go-varint"]
    version = "v0.0.6"
    hash = "sha256-QlY6AzrSB/8IrlINPi8J8uw1J0SOa2UMTtlo79fg9gM="
  [mod."github.com/nix-community/go-nix"]
    version = "v0.0.0-20220906172053-6b0185c1190b"
    hash = "sha256-ZzDh2KYGKBUc89kt41q8TqjWtGzikdb7bVto3So85FY="
  [mod."github.com/pbnjay/memory"]
    version = "v0.0.0-20210728143218-7b4eea64cf58"
    hash = "sha256-QI+F1oPLOOtwNp8+m45OOoSfYFs3QVjGzE0rFdpF/IA="
  [mod."github.com/pganalyze/pg_query_go/v2"]
    version = "v2.1.2"
    hash = "sha256-6/m7tUTKNkDxQxcIdpsjyrUqVeAKgfw9ZvLt3CdGJ8U="
  [mod."github.com/pingcap/errors"]
    version = "v0.11.5-0.20210425183316-da1aaba5fb63"
    hash = "sha256-DMCuYkR93VHzoR7UC4WhUGp4XGaEub4O0jAf+hAvljQ="
  [mod."github.com/pingcap/log"]
    version = "v0.0.0-20210906054005-afc726e70354"
    hash = "sha256-c+flCLgEnpgpNIhJbnrJ2QG64JT3Z/PopnKI+7VwevU="
  [mod."github.com/pingcap/tidb/parser"]
    version = "v0.0.0-20220725134311-c80026e61f00"
    hash = "sha256-va2hIG/5s7IlMBeK9GlgDCep23soGcRtRlvSI87eDsY="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pressly/goose"]
    version = "v2.7.0+incompatible"
    hash = "sha256-tIoIYGqFIkGxaVG0NM4DelK+iedlB8jgtEqWJiN+7K4="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.7.0"
    hash = "sha256-DrrEhyuFyfpfWodBV86LUNGNcRj2WxRfw/D/89C1rn8="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20220927061507-ef77025ab5aa"
    hash = "sha256-9A7mKiLofkxBKRctzSuUEdCiUeApUfp7Tgs/gPpNCzY="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/spf13/cobra"]
    version = "v1.5.0"
    hash = "sha256-rcyHWrxshA5DVpxrSba5X4NjppqOGrJ64QkUKKnfW2E="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/ziutek/mymysql"]
    version = "v1.5.4"
    hash = "sha256-kOAoAGINbmby8UhfxVvZPQ4tRQd92Tp96HyAPLE0cts="
  [mod."go.uber.org/atomic"]
    version = "v1.10.0"
    hash = "sha256-E6UEDc1eh/cLUFd+J86cDesQ0B8wEv/DdaAVKb+x2t8="
  [mod."go.uber.org/multierr"]
    version = "v1.8.0"
    hash = "sha256-WHWgw6hLI4tPKEqJt+WC38yt64OGCXfkUJDem6mM+Mw="
  [mod."go.uber.org/zap"]
    version = "v1.19.1"
    hash = "sha256-n4fccCHVtdrDpZSo98wQVrPl+vB/O1/hFC4htiV/Knk="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220926161630-eccd6366d1be"
    hash = "sha256-1a4f0LfmXChzVIrpRZaqIByorILGSjzEZZoL15Jn82Y="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20220927162542-c76eaa363f9d"
    hash = "sha256-qhNke47Mvnu3uIfLrfKqZ6Lqr7bt6dUXIruk8KkzdjE="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220826154423-83b083e8dc8b"
    hash = "sha256-50A1EeE7HxKbnLBy1vdxtrbH+7d6/mnZA0cOwHJr5XA="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220927170352-d9d178bc13c6"
    hash = "sha256-akJSo7biBpfJgZ83+ZLDp2E4vSXRQ0LTqtvtrId5YJk="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.0.0"
    hash = "sha256-CLir3wRkgNy7tXQWODk7u3RP/W7qIsO2LADdM6/vWtQ="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."lukechampine.com/blake3"]
    version = "v1.1.7"
    hash = "sha256-iAysW2prUQa7ieT4KASyIOsihyo0o9T7t6qBTKSnMn0="
  [mod."modernc.org/cc/v3"]
    version = "v3.39.0"
    hash = "sha256-dGbX29yylAw18eONnCnuutBh7qW9j0nSu1JBLExJ9CU="
  [mod."modernc.org/libc"]
    version = "v1.20.0"
    hash = "sha256-SvGTDPxO8FSEB5Nsx3DkuJf7SIPYFRpDz3kDd1KciTM="
  [mod."modernc.org/sqlite"]
    version = "v1.19.1"
    hash = "sha256-le9QaphFLa3tbYhVhdXDrL/ZNq4VCDMvnNAbW4V4fz0="
