name: CI

on:
  pull_request:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v10
      with:
        name: nix-community
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: build
      run: nix-shell --run "make"

    # Docs
    - name: build-doc
      run: nix-build ./. -A trustix-doc
    - name: deploy-doc
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./result
