name: python checks

on:
  pull_request:
  push:
    branches: master

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v10
      with:
        name: nix-community
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: black
      run: nix-shell --run "./checks/black"

    - name: mypy
      run: nix-shell --run "./checks/mypy"
